<#
.SYNOPSIS
  Deploy the public-endpoint cloud sample resources (SQL, Postgres, Cosmos).

.DESCRIPTION
  Reads ADMIN_LOGIN + ADMIN_OBJECT_ID from env (Entra-only auth, MCAPS rule).
  Creates the resource group if missing, then runs the bicep deployment.
  Echos the connection details into ../../../.env.cloud for the seeders + harvesters.

.EXAMPLE
  $env:ADMIN_LOGIN = "you@contoso.onmicrosoft.com"
  $env:ADMIN_OBJECT_ID = "00000000-0000-0000-0000-000000000000"
  ./deploy.ps1 -ResourceGroup rg-fbrlin-dev-cac -Location canadacentral
#>
param(
  [Parameter(Mandatory)] [string] $ResourceGroup,
  [string] $Location = 'canadacentral',
  [string] $SubscriptionId
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

if ($SubscriptionId) { az account set --subscription $SubscriptionId | Out-Null }

foreach ($var in @('ADMIN_LOGIN','ADMIN_OBJECT_ID')) {
  if (-not (Test-Path "env:$var")) {
    throw "Environment variable $var must be set before running deploy.ps1"
  }
}

Write-Host "Ensuring resource group $ResourceGroup in $Location..." -ForegroundColor Cyan
az group create --name $ResourceGroup --location $Location --output none

$bicep = Join-Path $PSScriptRoot 'main.bicep'
$param = Join-Path $PSScriptRoot 'main.bicepparam'

Write-Host "Deploying bicep..." -ForegroundColor Cyan
$deployment = az deployment group create `
  --resource-group $ResourceGroup `
  --template-file  $bicep `
  --parameters     $param `
  --output json | ConvertFrom-Json

if (-not $deployment) { throw "Deployment failed" }

$o = $deployment.properties.outputs
$envFile = Join-Path $PSScriptRoot '..' '..' '..' '.env.cloud'
$envFile = (Resolve-Path -LiteralPath $envFile -ErrorAction SilentlyContinue) ?? $envFile

@(
  "# Generated by samples/cloud/infra/deploy.ps1 at $(Get-Date -Format o)"
  "RG=$ResourceGroup"
  "LOCATION=$Location"
  "SQL_SERVER_FQDN=$($o.sqlServerFqdn.value)"
  "SQL_DATABASE=$($o.sqlDatabase.value)"
  "PG_SERVER_FQDN=$($o.pgServerFqdn.value)"
  "PG_DATABASE=$($o.pgDatabase.value)"
  "PG_ADMIN_LOGIN=$env:ADMIN_LOGIN"
  "COSMOS_ENDPOINT=$($o.cosmosEndpoint.value)"
  "COSMOS_DATABASE=$($o.cosmosDatabase.value)"
  "# Oracle is BYO - set ORACLE_DSN to an existing reachable instance"
  "ORACLE_DSN="
) | Set-Content -Path $envFile -Encoding utf8

Write-Host "Wrote connection details to $envFile" -ForegroundColor Green
Write-Host "Next: python samples/cloud/seed/run_all.py" -ForegroundColor Yellow
